### ISSUE TITLE
No changes reflected in json after rails boot

### ISSUE THREAD

**Issue by eelkevdbos** [fnando/i18n-json#2]
Using the following config:

```yaml
translations:
  - file: app/assets/locales/:locale/application.json
    patterns:
      - "*"
      - "!admin*"
      - "!rails*"
```

Initial translations are generated correctly using

```shell
$ I18nJSON.call(config_file: "config/i18n.yml")
```

However, subsequent changes to a locale file (in `config/locales`) do not change the json output. Even weirder, when I completely remove the json files previously outputted and reinvoke `I18nJSON.call` the old/original json is again generated. The same behavior holds for `I18nJSON.listen`.

**Important**: Rebooting rails and or starting a new rails console session does trigger actual changes, but only once for that session.
